#!/usr/bin/env python3
"""
Auto-generated HSK Vocabulary Data
Generated by HSKDataDownloader
"""

HSK_VOCABULARY = {
    "HSK 1": [
    ],
    "HSK 2": [
    ],
    "HSK 3": [
    ],
    "HSK 4": [
    ],
    "HSK 5": [
    ],
    "HSK 6": [
    ],
}
